### ISSUE TITLE
Avoid redundant Travis builds

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2141]
If you want to slightly reduce CI waiting time in pull requests, consider adding this to Travis:
```yaml
branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
```
This will run CI only on `master`, `gh-pages`, tags and branches whose name starts with `testing-`.  In this way pull requests opened from branches in this repository won't spawn 4 extra (mostly useless) CI jobs.

As I mentioned in #2139, consider also caching artifacts to further reduce CI time: https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484

_Originally posted by @giordano in https://github.com/JuliaReach/LazySets.jl/pull/2140#issuecomment-619085343_
